import type { Metadata } from 'next';
import { Inter, Bebas_Neue } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/organisms/Header';
import { Footer } from '@/components/molecules/Footer';

const inter = Inter({
  variable: '--inter',
  subsets: ['latin']
});

const bebasNeue = Bebas_Neue({
  variable: '--bebas-neue',
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: '⚡ Naianderson Bruno',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.variable} ${bebasNeue.variable}`}>
        <Header />
        <div className="max-w-[1200px] mx-auto px-8 mt-24">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
